# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from fanvue_sdk.resources.agencies import AgenciesResource
from fanvue_sdk.resources.chat_custom_list_members import ChatCustomListMembersResource
from fanvue_sdk.resources.chat_custom_lists import ChatCustomListsResource
from fanvue_sdk.resources.chat_messages import ChatMessagesResource
from fanvue_sdk.resources.chat_smart_lists import ChatSmartListsResource
from fanvue_sdk.resources.chat_templates import ChatTemplatesResource
from fanvue_sdk.resources.chats import ChatsResource
from fanvue_sdk.resources.creators import CreatorsResource
from fanvue_sdk.resources.insights import InsightsResource
from fanvue_sdk.resources.media import MediaResource
from fanvue_sdk.resources.posts import PostsResource
from fanvue_sdk.resources.tracking_links import TrackingLinksResource
from fanvue_sdk.resources.users import UsersResource
from fanvue_sdk.resources.vault import VaultResource

RESOURCE_FACTORIES = {
    'agencies': AgenciesResource,
    'chat_custom_list_members': ChatCustomListMembersResource,
    'chat_custom_lists': ChatCustomListsResource,
    'chat_messages': ChatMessagesResource,
    'chat_smart_lists': ChatSmartListsResource,
    'chat_templates': ChatTemplatesResource,
    'chats': ChatsResource,
    'creators': CreatorsResource,
    'insights': InsightsResource,
    'media': MediaResource,
    'posts': PostsResource,
    'tracking_links': TrackingLinksResource,
    'users': UsersResource,
    'vault': VaultResource,
}

__all__ = [
    'AgenciesResource',
    'ChatCustomListMembersResource',
    'ChatCustomListsResource',
    'ChatMessagesResource',
    'ChatSmartListsResource',
    'ChatTemplatesResource',
    'ChatsResource',
    'CreatorsResource',
    'InsightsResource',
    'MediaResource',
    'PostsResource',
    'TrackingLinksResource',
    'UsersResource',
    'VaultResource',
    'RESOURCE_FACTORIES',
]
