# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from fanvue_sdk.resources.agencies import AgenciesResource
from fanvue_sdk.resources.apps import AppsResource
from fanvue_sdk.resources.chats import ChatsResource
from fanvue_sdk.resources.collections import CollectionsResource
from fanvue_sdk.resources.creators import CreatorsResource
from fanvue_sdk.resources.followers import FollowersResource
from fanvue_sdk.resources.insights import InsightsResource
from fanvue_sdk.resources.media import MediaResource
from fanvue_sdk.resources.notifications import NotificationsResource
from fanvue_sdk.resources.posts import PostsResource
from fanvue_sdk.resources.subscribers import SubscribersResource
from fanvue_sdk.resources.tracking_links import TrackingLinksResource
from fanvue_sdk.resources.users import UsersResource
from fanvue_sdk.resources.vault import VaultResource

RESOURCE_FACTORIES = {
    'agencies': AgenciesResource,
    'apps': AppsResource,
    'chats': ChatsResource,
    'collections': CollectionsResource,
    'creators': CreatorsResource,
    'followers': FollowersResource,
    'insights': InsightsResource,
    'media': MediaResource,
    'notifications': NotificationsResource,
    'posts': PostsResource,
    'subscribers': SubscribersResource,
    'tracking_links': TrackingLinksResource,
    'users': UsersResource,
    'vault': VaultResource,
}

__all__ = [
    'AgenciesResource',
    'AppsResource',
    'ChatsResource',
    'CollectionsResource',
    'CreatorsResource',
    'FollowersResource',
    'InsightsResource',
    'MediaResource',
    'NotificationsResource',
    'PostsResource',
    'SubscribersResource',
    'TrackingLinksResource',
    'UsersResource',
    'VaultResource',
    'RESOURCE_FACTORIES',
]
