# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, cast

from fanvue_sdk.models import (
    CreateAgencyInviteResponse,
    CreateCreatorInviteResponse,
    GetChatterLeaderboardResponse,
    ListAgencyChatsResponse,
    ListAgencyEarningsByDayResponse,
    ListAgencySubscribersHistoryResponse,
    ListAgencySubscribersResponse,
    ListTeamMembersResponse,
    UpdateTeamMemberResponse,
)
from fanvue_sdk.resources.base import BaseResource


class AgenciesResource(BaseResource):
    """AgenciesResource endpoints."""

    async def create_agency_invite(self, *, body: Mapping[str, Any]) -> CreateAgencyInviteResponse:
        """
        Invite a team member

        `POST /agencies/invites`
        Docs: https://api.fanvue.com/docs/api-reference/reference/create-agency-invite
        """
        return cast(CreateAgencyInviteResponse, await self._client._call_operation(
            operation_id='create_agency_invite',
            body=body,
        ))

    async def create_creator_invite(self, *, body: Mapping[str, Any]) -> CreateCreatorInviteResponse:
        """
        Invite a creator

        `POST /agencies/creator-invites`
        Docs: https://api.fanvue.com/docs/api-reference/reference/create-creator-invite
        """
        return cast(CreateCreatorInviteResponse, await self._client._call_operation(
            operation_id='create_creator_invite',
            body=body,
        ))

    async def get_chatter_leaderboard(self, *, start_date: str | None = None, end_date: str | None = None, chatter_uuids: str | None = None) -> GetChatterLeaderboardResponse:
        """
        Get chatter leaderboard

        `GET /agencies/insights/chatter-leaderboard`
        Docs: https://api.fanvue.com/docs/api-reference/reference/get-chatter-leaderboard
        """
        return cast(GetChatterLeaderboardResponse, await self._client._call_operation(
            operation_id='get_chatter_leaderboard',
            query_params={
                'startDate': start_date,
                'endDate': end_date,
                'chatterUuids': chatter_uuids,
            },
        ))

    async def list_agency_chats(self, *, page: float | None = None, size: float | None = None) -> ListAgencyChatsResponse:
        """
        List chats across all agency creators

        `GET /agencies/chats`
        Docs: https://api.fanvue.com/docs/api-reference/reference/list-agency-chats
        """
        return cast(ListAgencyChatsResponse, await self._client._call_operation(
            operation_id='list_agency_chats',
            query_params={
                'page': page,
                'size': size,
            },
        ))

    async def list_agency_earnings_by_day(self, *, start_date: str, end_date: str, page: float | None = None, size: float | None = None, creator_uuids: Sequence[str] | None = None) -> ListAgencyEarningsByDayResponse:
        """
        List per-creator-per-day earnings across all agency creators

        `GET /agencies/earnings`
        Docs: https://api.fanvue.com/docs/api-reference/reference/list-agency-earnings-by-day
        """
        return cast(ListAgencyEarningsByDayResponse, await self._client._call_operation(
            operation_id='list_agency_earnings_by_day',
            query_params={
                'page': page,
                'size': size,
                'startDate': start_date,
                'endDate': end_date,
                'creatorUuids': creator_uuids,
            },
        ))

    async def list_agency_subscribers(self, *, page: float | None = None, size: float | None = None, creator_uuids: Sequence[str] | None = None) -> ListAgencySubscribersResponse:
        """
        List active subscribers across all agency creators

        `GET /agencies/subscribers`
        Docs: https://api.fanvue.com/docs/api-reference/reference/list-agency-subscribers
        """
        return cast(ListAgencySubscribersResponse, await self._client._call_operation(
            operation_id='list_agency_subscribers',
            query_params={
                'page': page,
                'size': size,
                'creatorUuids': creator_uuids,
            },
        ))

    async def list_agency_subscribers_history(self, *, start_date: str, end_date: str, page: float | None = None, size: float | None = None, creator_uuids: Sequence[str] | None = None) -> ListAgencySubscribersHistoryResponse:
        """
        List per-creator-per-day subscriber events across all agency creators

        `GET /agencies/subscribers-history`
        Docs: https://api.fanvue.com/docs/api-reference/reference/list-agency-subscribers-history
        """
        return cast(ListAgencySubscribersHistoryResponse, await self._client._call_operation(
            operation_id='list_agency_subscribers_history',
            query_params={
                'page': page,
                'size': size,
                'startDate': start_date,
                'endDate': end_date,
                'creatorUuids': creator_uuids,
            },
        ))

    async def list_team_members(self) -> ListTeamMembersResponse:
        """
        List team members

        `GET /agencies/team-members`
        Docs: https://api.fanvue.com/docs/api-reference/reference/list-team-members
        """
        return cast(ListTeamMembersResponse, await self._client._call_operation(
            operation_id='list_team_members',
        ))

    async def update_team_member(self, user_id: str, *, body: Mapping[str, Any]) -> UpdateTeamMemberResponse:
        """
        Update team member

        `PUT /agencies/team-members/{userId}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/update-team-member
        """
        return cast(UpdateTeamMemberResponse, await self._client._call_operation(
            operation_id='update_team_member',
            path_params={
                'userId': user_id,
            },
            body=body,
        ))
