# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from typing import cast

from fanvue_sdk.models import (
    GetAppCurrentUserSubscriptionResponse,
    GetAppSubscriptionStatusResponse,
)
from fanvue_sdk.resources.base import BaseResource


class AppsResource(BaseResource):
    """AppsResource endpoints."""

    async def get_app_current_user_subscription(self, app_uuid: str) -> GetAppCurrentUserSubscriptionResponse:
        """
        Get current user subscription for an installed app

        `GET /apps/{appUuid}/subscription/me`
        Docs: https://api.fanvue.com/docs/api-reference/reference/get-app-current-user-subscription
        """
        return cast(GetAppCurrentUserSubscriptionResponse, await self._client._call_operation(
            operation_id='get_app_current_user_subscription',
            path_params={
                'appUuid': app_uuid,
            },
        ))

    async def get_app_subscription_status(self, app_uuid: str) -> GetAppSubscriptionStatusResponse:
        """
        Get app pricing subscription lifecycle status

        `GET /apps/{appUuid}/subscription-status`
        Docs: https://api.fanvue.com/docs/api-reference/reference/get-app-subscription-status
        """
        return cast(GetAppSubscriptionStatusResponse, await self._client._call_operation(
            operation_id='get_app_subscription_status',
            path_params={
                'appUuid': app_uuid,
            },
        ))
