# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from typing import cast

from fanvue_sdk.models import (
    GetTemplateMessageResponse,
    ListTemplateMessagesResponse,
)
from fanvue_sdk.resources.base import BaseResource


class ChatTemplatesResource(BaseResource):
    """ChatTemplatesResource endpoints."""

    async def get_template_message(self, template_uuid: str) -> GetTemplateMessageResponse:
        """
        Get a single template message

        `GET /chats/templates/{templateUuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-templates/get-template-message
        """
        return cast(GetTemplateMessageResponse, await self._client._call_operation(
            operation_id='get_template_message',
            path_params={
                'templateUuid': template_uuid,
            },
        ))

    async def list_template_messages(self, *, page: float | None = None, size: float | None = None, folder_name: str | None = None) -> ListTemplateMessagesResponse:
        """
        Get list of template messages

        `GET /chats/templates`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-templates/list-template-messages
        """
        return cast(ListTemplateMessagesResponse, await self._client._call_operation(
            operation_id='list_template_messages',
            query_params={
                'page': page,
                'size': size,
                'folderName': folder_name,
            },
        ))
