# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Literal, cast

from fanvue_sdk.models import (
    ListMessagesResponse,
    SendMassMessageResponse,
    SendMessageResponse,
)
from fanvue_sdk.resources.base import BaseResource


class ChatMessagesResource(BaseResource):
    """ChatMessagesResource endpoints."""

    async def delete_message(self, user_uuid: str, message_uuid: str) -> None:
        """
        Delete a message

        `DELETE /chats/{userUuid}/messages/{messageUuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-messages/delete-message
        """
        await self._client._call_operation(
            operation_id='delete_message',
            path_params={
                'userUuid': user_uuid,
                'messageUuid': message_uuid,
            },
        )
        return None

    async def list_messages(self, user_uuid: str, *, page: float | None = None, size: float | None = None, mark_as_read: Literal['true', 'false'] | None = None) -> ListMessagesResponse:
        """
        Get messages from a chat

        `GET /chats/{userUuid}/messages`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-messages/list-messages
        """
        return cast(ListMessagesResponse, await self._client._call_operation(
            operation_id='list_messages',
            path_params={
                'userUuid': user_uuid,
            },
            query_params={
                'page': page,
                'size': size,
                'markAsRead': mark_as_read,
            },
        ))

    async def send_mass_message(self, *, body: Mapping[str, Any] | None = None) -> SendMassMessageResponse:
        """
        Send a mass message

        `POST /chats/mass-messages`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-messages/send-mass-message
        """
        return cast(SendMassMessageResponse, await self._client._call_operation(
            operation_id='send_mass_message',
            body=body,
        ))

    async def send_message(self, user_uuid: str, *, body: Mapping[str, Any] | None = None) -> SendMessageResponse:
        """
        Send a message

        `POST /chats/{userUuid}/message`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-messages/send-message
        """
        return cast(SendMessageResponse, await self._client._call_operation(
            operation_id='send_message',
            path_params={
                'userUuid': user_uuid,
            },
            body=body,
        ))
