# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, cast

from fanvue_sdk.models import (
    CreateCustomListResponse,
    GetCustomListMembersResponse,
    GetCustomListsResponse,
)
from fanvue_sdk.resources.base import BaseResource


class ChatCustomListsResource(BaseResource):
    """ChatCustomListsResource endpoints."""

    async def create_custom_list(self, *, body: Mapping[str, Any] | None = None) -> CreateCustomListResponse:
        """
        Create a custom list

        `POST /chats/lists/custom`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-custom-lists/create-custom-list
        """
        return cast(CreateCustomListResponse, await self._client._call_operation(
            operation_id='create_custom_list',
            body=body,
        ))

    async def delete_custom_list(self, uuid: str) -> None:
        """
        Delete a custom list

        `DELETE /chats/lists/custom/{uuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-custom-lists/delete-custom-list
        """
        await self._client._call_operation(
            operation_id='delete_custom_list',
            path_params={
                'uuid': uuid,
            },
        )
        return None

    async def get_custom_list_members(self, uuid: str, *, page: float | None = None, size: float | None = None) -> GetCustomListMembersResponse:
        """
        Get custom list members

        `GET /chats/lists/custom/{uuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-custom-lists/get-custom-list-members
        """
        return cast(GetCustomListMembersResponse, await self._client._call_operation(
            operation_id='get_custom_list_members',
            path_params={
                'uuid': uuid,
            },
            query_params={
                'page': page,
                'size': size,
            },
        ))

    async def get_custom_lists(self, *, page: float | None = None, size: float | None = None, search: str | None = None) -> GetCustomListsResponse:
        """
        Get custom lists

        `GET /chats/lists/custom`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-custom-lists/get-custom-lists
        """
        return cast(GetCustomListsResponse, await self._client._call_operation(
            operation_id='get_custom_lists',
            query_params={
                'page': page,
                'size': size,
                'search': search,
            },
        ))

    async def update_custom_list(self, uuid: str, *, body: Mapping[str, Any] | None = None) -> None:
        """
        Rename a custom list

        `PATCH /chats/lists/custom/{uuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-custom-lists/update-custom-list
        """
        await self._client._call_operation(
            operation_id='update_custom_list',
            path_params={
                'uuid': uuid,
            },
            body=body,
        )
        return None
