# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from typing import Literal, cast

from fanvue_sdk.models import (
    GetSmartListMembersResponse,
    GetSmartListsResponse,
)
from fanvue_sdk.resources.base import BaseResource


class ChatSmartListsResource(BaseResource):
    """ChatSmartListsResource endpoints."""

    async def get_smart_list_members(self, uuid: Literal['subscribers', 'auto_renewing', 'non_renewing', 'followers', 'free_trial_subscribers', 'expired_subscribers', 'spent_more_than_50'], *, page: float | None = None, size: float | None = None) -> GetSmartListMembersResponse:
        """
        Get smart list members

        `GET /chats/lists/smart/{uuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-smart-lists/get-smart-list-members
        """
        return cast(GetSmartListMembersResponse, await self._client._call_operation(
            operation_id='get_smart_list_members',
            path_params={
                'uuid': uuid,
            },
            query_params={
                'page': page,
                'size': size,
            },
        ))

    async def get_smart_lists(self) -> GetSmartListsResponse:
        """
        Get smart lists

        `GET /chats/lists/smart`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-smart-lists/get-smart-lists
        """
        return cast(GetSmartListsResponse, await self._client._call_operation(
            operation_id='get_smart_lists',
        ))
