# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, cast

from fanvue_sdk.models import (
    AddMembersToCustomListResponse,
)
from fanvue_sdk.resources.base import BaseResource


class ChatCustomListMembersResource(BaseResource):
    """ChatCustomListMembersResource endpoints."""

    async def add_members_to_custom_list(self, uuid: str, *, body: Mapping[str, Any] | None = None) -> AddMembersToCustomListResponse:
        """
        Add members to a custom list

        `POST /chats/lists/custom/{uuid}/members`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-custom-list-members/add-members-to-custom-list
        """
        return cast(AddMembersToCustomListResponse, await self._client._call_operation(
            operation_id='add_members_to_custom_list',
            path_params={
                'uuid': uuid,
            },
            body=body,
        ))

    async def remove_member_from_custom_list(self, uuid: str, user_uuid: str) -> None:
        """
        Remove a member from a custom list

        `DELETE /chats/lists/custom/{uuid}/members/{userUuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chat-custom-list-members/remove-member-from-custom-list
        """
        await self._client._call_operation(
            operation_id='remove_member_from_custom_list',
            path_params={
                'uuid': uuid,
                'userUuid': user_uuid,
            },
        )
        return None
