# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Literal, cast

from fanvue_sdk.models import (
    CreateChatResponse,
    GetBatchStatusesResponse,
    GetUnreadChatsCountResponse,
    ListChatsResponse,
    ListMediaResponse,
)
from fanvue_sdk.resources.base import BaseResource


class ChatsResource(BaseResource):
    """ChatsResource endpoints."""

    async def create_chat(self, *, body: Mapping[str, Any] | None = None) -> CreateChatResponse:
        """
        Create a new chat

        `POST /chats`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chats/create-chat
        """
        return cast(CreateChatResponse, await self._client._call_operation(
            operation_id='create_chat',
            body=body,
        ))

    async def get_batch_statuses(self, *, body: Mapping[str, Any] | None = None) -> GetBatchStatusesResponse:
        """
        Get online statuses for multiple users

        `POST /chats/statuses`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chats/get-batch-statuses
        """
        return cast(GetBatchStatusesResponse, await self._client._call_operation(
            operation_id='get_batch_statuses',
            body=body,
        ))

    async def get_unread_chats_count(self) -> GetUnreadChatsCountResponse:
        """
        Get unread chats, messages, and notifications count

        `GET /chats/unread`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chats/get-unread-chats-count
        """
        return cast(GetUnreadChatsCountResponse, await self._client._call_operation(
            operation_id='get_unread_chats_count',
        ))

    async def list_chats(self, *, page: float | None = None, size: float | None = None, custom_list_id: str | None = None, smart_list_ids: Sequence[Literal['subscribers', 'auto_renewing', 'non_renewing', 'followers', 'free_trial_subscribers', 'expired_subscribers', 'spent_more_than_50']] | None = None, filter: Sequence[Literal['unread', 'subscribers', 'followers', 'online', 'recent_subscribers', 'not_answered', 'spent_more_than_50', 'on_free_trial', 'has_tipped', 'spenders', 'exclude_creators', 'subscribed_to', 'not_muted']] | None = None, search: str | None = None, sort_by: Literal['most_recent_messages', 'online_now', 'most_unanswered_chats'] | None = None) -> ListChatsResponse:
        """
        Get list of chats

        `GET /chats`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chats/list-chats
        """
        return cast(ListChatsResponse, await self._client._call_operation(
            operation_id='list_chats',
            query_params={
                'page': page,
                'size': size,
                'customListId': custom_list_id,
                'smartListIds': smart_list_ids,
                'filter': filter,
                'search': search,
                'sortBy': sort_by,
            },
        ))

    async def list_media(self, user_uuid: str, *, cursor: str | None = None, media_type: Literal['image', 'video', 'audio', 'document'] | None = None, limit: float | None = None) -> ListMediaResponse:
        """
        Get media from a chat

        `GET /chats/{userUuid}/media`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chats/list-media
        """
        return cast(ListMediaResponse, await self._client._call_operation(
            operation_id='list_media',
            path_params={
                'userUuid': user_uuid,
            },
            query_params={
                'cursor': cursor,
                'mediaType': media_type,
                'limit': limit,
            },
        ))

    async def update_chat(self, user_uuid: str, *, body: Mapping[str, Any] | None = None) -> None:
        """
        Update chat properties

        `PATCH /chats/{userUuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/chats/update-chat
        """
        await self._client._call_operation(
            operation_id='update_chat',
            path_params={
                'userUuid': user_uuid,
            },
            body=body,
        )
        return None
