# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, cast

from fanvue_sdk.models import (
    CreateCollectionResponse,
    ListCollectionsResponse,
)
from fanvue_sdk.resources.base import BaseResource


class CollectionsResource(BaseResource):
    """CollectionsResource endpoints."""

    async def create_collection(self, *, body: Mapping[str, Any]) -> CreateCollectionResponse:
        """
        Create a content collection

        `POST /collections`
        Docs: https://api.fanvue.com/docs/api-reference/reference/create-collection
        """
        return cast(CreateCollectionResponse, await self._client._call_operation(
            operation_id='create_collection',
            body=body,
        ))

    async def delete_collection(self, uuid: str) -> None:
        """
        Delete a content collection

        `DELETE /collections/{uuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/delete-collection
        """
        await self._client._call_operation(
            operation_id='delete_collection',
            path_params={
                'uuid': uuid,
            },
        )
        return None

    async def list_collections(self) -> ListCollectionsResponse:
        """
        List content collections

        `GET /collections`
        Docs: https://api.fanvue.com/docs/api-reference/reference/list-collections
        """
        return cast(ListCollectionsResponse, await self._client._call_operation(
            operation_id='list_collections',
        ))

    async def rename_collection(self, uuid: str, *, body: Mapping[str, Any]) -> None:
        """
        Rename a content collection

        `PATCH /collections/{uuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/rename-collection
        """
        await self._client._call_operation(
            operation_id='rename_collection',
            path_params={
                'uuid': uuid,
            },
            body=body,
        )
        return None
