# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, cast

from fanvue_sdk.models import (
    ListFollowersResponse,
    ListSubscribersResponse,
)
from fanvue_sdk.resources.base import BaseResource


class CreatorsResource(BaseResource):
    """CreatorsResource endpoints."""

    async def list_followers(self, *, page: float | None = None, size: float | None = None) -> ListFollowersResponse:
        """
        Get followers

        `GET /followers`
        Docs: https://api.fanvue.com/docs/api-reference/reference/creators/list-followers
        """
        return cast(ListFollowersResponse, await self._client._call_operation(
            operation_id='list_followers',
            query_params={
                'page': page,
                'size': size,
            },
        ))

    async def list_subscribers(self, *, page: float | None = None, size: float | None = None) -> ListSubscribersResponse:
        """
        Get subscribers

        `GET /subscribers`
        Docs: https://api.fanvue.com/docs/api-reference/reference/creators/list-subscribers
        """
        return cast(ListSubscribersResponse, await self._client._call_operation(
            operation_id='list_subscribers',
            query_params={
                'page': page,
                'size': size,
            },
        ))

    async def update_creator_chat(self, creator_user_uuid: str, user_uuid: str, *, body: Mapping[str, Any] | None = None) -> None:
        """
        Update a creator's chat with a user

        `PATCH /creators/{creatorUserUuid}/chats/{userUuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/update-creator-chat
        """
        await self._client._call_operation(
            operation_id='update_creator_chat',
            path_params={
                'creatorUserUuid': creator_user_uuid,
                'userUuid': user_uuid,
            },
            body=body,
        )
        return None
