# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from typing import cast

from fanvue_sdk.models import (
    ListFollowersResponse,
)
from fanvue_sdk.resources.base import BaseResource


class FollowersResource(BaseResource):
    """FollowersResource endpoints."""

    async def list_followers(self, *, page: float | None = None, size: float | None = None) -> ListFollowersResponse:
        """
        Get followers

        `GET /followers`
        Docs: https://api.fanvue.com/docs/api-reference/reference/list-followers
        """
        return cast(ListFollowersResponse, await self._client._call_operation(
            operation_id='list_followers',
            query_params={
                'page': page,
                'size': size,
            },
        ))
