# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Sequence
from typing import Literal, cast

from fanvue_sdk.models import (
    GetEarningsResponse,
    GetFanInsightsResponse,
    GetSubscribersResponse,
    GetTopSpendersResponse,
)
from fanvue_sdk.resources.base import BaseResource


class InsightsResource(BaseResource):
    """InsightsResource endpoints."""

    async def get_earnings(self, *, start_date: str | None = None, end_date: str | None = None, source: Sequence[Literal['all', 'affiliate', 'mediaLink', 'message', 'post', 'referral', 'renewal', 'subscription', 'tip', 'giveaway']] | None = None, cursor: str | None = None, size: float | None = None) -> GetEarningsResponse:
        """
        Get earnings data

        `GET /insights/earnings`
        Docs: https://api.fanvue.com/docs/api-reference/reference/insights/get-earnings
        """
        return cast(GetEarningsResponse, await self._client._call_operation(
            operation_id='get_earnings',
            query_params={
                'startDate': start_date,
                'endDate': end_date,
                'source': source,
                'cursor': cursor,
                'size': size,
            },
        ))

    async def get_fan_insights(self, user_uuid: str) -> GetFanInsightsResponse:
        """
        Get fan insights

        `GET /insights/fans/{userUuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/insights/get-fan-insights
        """
        return cast(GetFanInsightsResponse, await self._client._call_operation(
            operation_id='get_fan_insights',
            path_params={
                'userUuid': user_uuid,
            },
        ))

    async def get_subscribers(self, *, start_date: str | None = None, end_date: str | None = None, cursor: str | None = None, size: float | None = None) -> GetSubscribersResponse:
        """
        Get subscribers count

        `GET /insights/subscribers`
        Docs: https://api.fanvue.com/docs/api-reference/reference/insights/get-subscribers
        """
        return cast(GetSubscribersResponse, await self._client._call_operation(
            operation_id='get_subscribers',
            query_params={
                'startDate': start_date,
                'endDate': end_date,
                'cursor': cursor,
                'size': size,
            },
        ))

    async def get_top_spenders(self, *, start_date: str | None = None, end_date: str | None = None, page: float | None = None, size: float | None = None) -> GetTopSpendersResponse:
        """
        Get top-spending fans

        `GET /insights/top-spenders`
        Docs: https://api.fanvue.com/docs/api-reference/reference/insights/get-top-spenders
        """
        return cast(GetTopSpendersResponse, await self._client._call_operation(
            operation_id='get_top_spenders',
            query_params={
                'startDate': start_date,
                'endDate': end_date,
                'page': page,
                'size': size,
            },
        ))
