# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Literal, cast

from fanvue_sdk.models import (
    CompleteUploadSessionResponse,
    CreateUploadSessionResponse,
    GetUploadPartUrlResponse,
    GetUserMediaByUuidResponse,
    GetUserMediaResponse,
)
from fanvue_sdk.resources.base import BaseResource


class MediaResource(BaseResource):
    """MediaResource endpoints."""

    async def complete_upload_session(self, upload_id: str, *, body: Mapping[str, Any] | None = None) -> CompleteUploadSessionResponse:
        """
        Complete upload session

        `PATCH /media/uploads/{uploadId}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/media/complete-upload-session
        """
        return cast(CompleteUploadSessionResponse, await self._client._call_operation(
            operation_id='complete_upload_session',
            path_params={
                'uploadId': upload_id,
            },
            body=body,
        ))

    async def create_upload_session(self, *, body: Mapping[str, Any] | None = None) -> CreateUploadSessionResponse:
        """
        Create multipart upload session

        `POST /media/uploads`
        Docs: https://api.fanvue.com/docs/api-reference/reference/media/create-upload-session
        """
        return cast(CreateUploadSessionResponse, await self._client._call_operation(
            operation_id='create_upload_session',
            body=body,
        ))

    async def get_upload_part_url(self, upload_id: str, part_number: float) -> GetUploadPartUrlResponse:
        """
        Get signed URL for upload part

        `GET /media/uploads/{uploadId}/parts/{partNumber}/url`
        Docs: https://api.fanvue.com/docs/api-reference/reference/media/get-upload-part-url
        """
        return cast(GetUploadPartUrlResponse, await self._client._call_operation(
            operation_id='get_upload_part_url',
            path_params={
                'uploadId': upload_id,
                'partNumber': part_number,
            },
        ))

    async def get_user_media(self, *, page: float | None = None, size: float | None = None, media_type: Literal['image', 'video', 'audio', 'document'] | None = None, folder_name: str | None = None, usage: Literal['subscribers', 'followers', 'ppv', 'mass_messages'] | None = None, purchased_by: str | None = None, status: Sequence[Literal['created', 'processing', 'ready', 'error']] | None = None, variants: Sequence[Literal['blurred', 'main', 'thumbnail', 'thumbnail_gallery']] | None = None) -> GetUserMediaResponse:
        """
        Get user's media list

        `GET /media`
        Docs: https://api.fanvue.com/docs/api-reference/reference/media/get-user-media
        """
        return cast(GetUserMediaResponse, await self._client._call_operation(
            operation_id='get_user_media',
            query_params={
                'page': page,
                'size': size,
                'mediaType': media_type,
                'folderName': folder_name,
                'usage': usage,
                'purchasedBy': purchased_by,
                'status': status,
                'variants': variants,
            },
        ))

    async def get_user_media_by_uuid(self, uuid: str, *, purchased_by: str | None = None, variants: Sequence[Literal['blurred', 'main', 'thumbnail', 'thumbnail_gallery']] | None = None) -> GetUserMediaByUuidResponse:
        """
        Get media by UUID

        `GET /media/{uuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/media/get-user-media-by-uuid
        """
        return cast(GetUserMediaByUuidResponse, await self._client._call_operation(
            operation_id='get_user_media_by_uuid',
            path_params={
                'uuid': uuid,
            },
            query_params={
                'purchasedBy': purchased_by,
                'variants': variants,
            },
        ))
