# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from typing import cast

from fanvue_sdk.models import (
    ListNotificationsResponse,
)
from fanvue_sdk.resources.base import BaseResource


class NotificationsResource(BaseResource):
    """NotificationsResource endpoints."""

    async def list_notifications(self, *, page: float | None = None, size: float | None = None, event_type: int | None = None) -> ListNotificationsResponse:
        """
        Get notifications feed

        `GET /notifications`
        Docs: https://api.fanvue.com/docs/api-reference/reference/list-notifications
        """
        return cast(ListNotificationsResponse, await self._client._call_operation(
            operation_id='list_notifications',
            query_params={
                'page': page,
                'size': size,
                'eventType': event_type,
            },
        ))
