# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, cast

from fanvue_sdk.models import (
    CreatePostResponse,
    GetPostByUuidResponse,
    GetPostCommentsResponse,
    GetPostLikesResponse,
    GetPostsResponse,
    GetPostTipsResponse,
)
from fanvue_sdk.resources.base import BaseResource


class PostsResource(BaseResource):
    """PostsResource endpoints."""

    async def create_post(self, *, body: Mapping[str, Any] | None = None) -> CreatePostResponse:
        """
        Create a new post

        `POST /posts`
        Docs: https://api.fanvue.com/docs/api-reference/reference/posts/create-post
        """
        return cast(CreatePostResponse, await self._client._call_operation(
            operation_id='create_post',
            body=body,
        ))

    async def get_post_by_uuid(self, uuid: str) -> GetPostByUuidResponse:
        """
        Get post by UUID

        `GET /posts/{uuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/posts/get-post-by-uuid
        """
        return cast(GetPostByUuidResponse, await self._client._call_operation(
            operation_id='get_post_by_uuid',
            path_params={
                'uuid': uuid,
            },
        ))

    async def get_post_comments(self, uuid: str, *, page: float | None = None, size: float | None = None) -> GetPostCommentsResponse:
        """
        Get comments for a post

        `GET /posts/{uuid}/comments`
        Docs: https://api.fanvue.com/docs/api-reference/reference/posts/get-post-comments
        """
        return cast(GetPostCommentsResponse, await self._client._call_operation(
            operation_id='get_post_comments',
            path_params={
                'uuid': uuid,
            },
            query_params={
                'page': page,
                'size': size,
            },
        ))

    async def get_post_likes(self, uuid: str, *, page: float | None = None, size: float | None = None) -> GetPostLikesResponse:
        """
        Get likes for a post

        `GET /posts/{uuid}/likes`
        Docs: https://api.fanvue.com/docs/api-reference/reference/posts/get-post-likes
        """
        return cast(GetPostLikesResponse, await self._client._call_operation(
            operation_id='get_post_likes',
            path_params={
                'uuid': uuid,
            },
            query_params={
                'page': page,
                'size': size,
            },
        ))

    async def get_post_tips(self, uuid: str, *, page: float | None = None, size: float | None = None) -> GetPostTipsResponse:
        """
        Get tips for a post

        `GET /posts/{uuid}/tips`
        Docs: https://api.fanvue.com/docs/api-reference/reference/posts/get-post-tips
        """
        return cast(GetPostTipsResponse, await self._client._call_operation(
            operation_id='get_post_tips',
            path_params={
                'uuid': uuid,
            },
            query_params={
                'page': page,
                'size': size,
            },
        ))

    async def get_posts(self, *, page: float | None = None, size: float | None = None) -> GetPostsResponse:
        """
        Get list of posts

        `GET /posts`
        Docs: https://api.fanvue.com/docs/api-reference/reference/posts/get-posts
        """
        return cast(GetPostsResponse, await self._client._call_operation(
            operation_id='get_posts',
            query_params={
                'page': page,
                'size': size,
            },
        ))
