# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from typing import Literal, cast

from fanvue_sdk.models import (
    ListSubscribersResponse,
)
from fanvue_sdk.resources.base import BaseResource


class SubscribersResource(BaseResource):
    """SubscribersResource endpoints."""

    async def list_subscribers(self, *, page: float | None = None, size: float | None = None, sort_field: Literal['name', 'subscribedAt'] | None = None, sort_direction: Literal['asc', 'desc'] | None = None) -> ListSubscribersResponse:
        """
        Get subscribers

        `GET /subscribers`
        Docs: https://api.fanvue.com/docs/api-reference/reference/list-subscribers
        """
        return cast(ListSubscribersResponse, await self._client._call_operation(
            operation_id='list_subscribers',
            query_params={
                'page': page,
                'size': size,
                'sortField': sort_field,
                'sortDirection': sort_direction,
            },
        ))
