# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, cast

from fanvue_sdk.models import (
    CreateTrackingLinkResponse,
    ListTrackingLinksResponse,
)
from fanvue_sdk.resources.base import BaseResource


class TrackingLinksResource(BaseResource):
    """TrackingLinksResource endpoints."""

    async def create_tracking_link(self, *, body: Mapping[str, Any] | None = None) -> CreateTrackingLinkResponse:
        """
        Create a tracking link

        `POST /tracking-links`
        Docs: https://api.fanvue.com/docs/api-reference/reference/tracking-links/create-tracking-link
        """
        return cast(CreateTrackingLinkResponse, await self._client._call_operation(
            operation_id='create_tracking_link',
            body=body,
        ))

    async def delete_tracking_link(self, uuid: str) -> None:
        """
        Delete a tracking link

        `DELETE /tracking-links/{uuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/tracking-links/delete-tracking-link
        """
        await self._client._call_operation(
            operation_id='delete_tracking_link',
            path_params={
                'uuid': uuid,
            },
        )
        return None

    async def list_tracking_links(self, *, limit: int | None = None, cursor: str | None = None, created_after: str | None = None, created_before: str | None = None) -> ListTrackingLinksResponse:
        """
        List tracking links

        `GET /tracking-links`
        Docs: https://api.fanvue.com/docs/api-reference/reference/tracking-links/list-tracking-links
        """
        return cast(ListTrackingLinksResponse, await self._client._call_operation(
            operation_id='list_tracking_links',
            query_params={
                'limit': limit,
                'cursor': cursor,
                'createdAfter': created_after,
                'createdBefore': created_before,
            },
        ))
