# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from typing import cast

from fanvue_sdk.models import (
    GetCurrentUserResponse,
)
from fanvue_sdk.resources.base import BaseResource


class UsersResource(BaseResource):
    """UsersResource endpoints."""

    async def get_current_user(self) -> GetCurrentUserResponse:
        """
        Get current user

        `GET /users/me`
        Docs: https://api.fanvue.com/docs/api-reference/reference/users/get-current-user
        """
        return cast(GetCurrentUserResponse, await self._client._call_operation(
            operation_id='get_current_user',
        ))
