# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, cast

from fanvue_sdk.models import (
    AttachMediaToVaultFolderResponse,
    CreateVaultFolderResponse,
    GetVaultFolderResponse,
    ListVaultFolderMediaResponse,
    ListVaultFoldersResponse,
)
from fanvue_sdk.resources.base import BaseResource


class VaultResource(BaseResource):
    """VaultResource endpoints."""

    async def attach_media_to_vault_folder(self, folder_name: str, *, body: Mapping[str, Any] | None = None) -> AttachMediaToVaultFolderResponse:
        """
        Add media to folder

        `POST /vault/folders/{folderName}/media`
        Docs: https://api.fanvue.com/docs/api-reference/reference/vault/attach-media-to-vault-folder
        """
        return cast(AttachMediaToVaultFolderResponse, await self._client._call_operation(
            operation_id='attach_media_to_vault_folder',
            path_params={
                'folderName': folder_name,
            },
            body=body,
        ))

    async def create_vault_folder(self, *, body: Mapping[str, Any] | None = None) -> CreateVaultFolderResponse:
        """
        Create a vault folder

        `POST /vault/folders`
        Docs: https://api.fanvue.com/docs/api-reference/reference/vault/create-vault-folder
        """
        return cast(CreateVaultFolderResponse, await self._client._call_operation(
            operation_id='create_vault_folder',
            body=body,
        ))

    async def delete_vault_folder(self, folder_name: str) -> None:
        """
        Delete vault folder

        `DELETE /vault/folders/{folderName}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/vault/delete-vault-folder
        """
        await self._client._call_operation(
            operation_id='delete_vault_folder',
            path_params={
                'folderName': folder_name,
            },
        )
        return None

    async def detach_media_from_vault_folder(self, folder_name: str, media_uuid: str) -> None:
        """
        Remove media from folder

        `DELETE /vault/folders/{folderName}/media/{mediaUuid}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/vault/detach-media-from-vault-folder
        """
        await self._client._call_operation(
            operation_id='detach_media_from_vault_folder',
            path_params={
                'folderName': folder_name,
                'mediaUuid': media_uuid,
            },
        )
        return None

    async def get_vault_folder(self, folder_name: str) -> GetVaultFolderResponse:
        """
        Get vault folder details

        `GET /vault/folders/{folderName}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/vault/get-vault-folder
        """
        return cast(GetVaultFolderResponse, await self._client._call_operation(
            operation_id='get_vault_folder',
            path_params={
                'folderName': folder_name,
            },
        ))

    async def list_vault_folder_media(self, folder_name: str, *, page: float | None = None, size: float | None = None) -> ListVaultFolderMediaResponse:
        """
        List media in folder

        `GET /vault/folders/{folderName}/media`
        Docs: https://api.fanvue.com/docs/api-reference/reference/vault/list-vault-folder-media
        """
        return cast(ListVaultFolderMediaResponse, await self._client._call_operation(
            operation_id='list_vault_folder_media',
            path_params={
                'folderName': folder_name,
            },
            query_params={
                'page': page,
                'size': size,
            },
        ))

    async def list_vault_folders(self) -> ListVaultFoldersResponse:
        """
        List vault folders

        `GET /vault/folders`
        Docs: https://api.fanvue.com/docs/api-reference/reference/vault/list-vault-folders
        """
        return cast(ListVaultFoldersResponse, await self._client._call_operation(
            operation_id='list_vault_folders',
        ))

    async def rename_vault_folder(self, folder_name: str, *, body: Mapping[str, Any] | None = None) -> None:
        """
        Rename vault folder

        `PATCH /vault/folders/{folderName}`
        Docs: https://api.fanvue.com/docs/api-reference/reference/vault/rename-vault-folder
        """
        await self._client._call_operation(
            operation_id='rename_vault_folder',
            path_params={
                'folderName': folder_name,
            },
            body=body,
        )
        return None
