# This file is auto-generated by scripts/generate_sdk.py

from __future__ import annotations

from typing import Any, Literal, TypeAlias

from pydantic import BaseModel, ConfigDict, TypeAdapter

from fanvue_sdk.types import ResponseData


class FanvueModel(BaseModel):
    """Base model for generated Fanvue response payloads."""

    model_config = ConfigDict(extra='allow', populate_by_name=True)


class GetCurrentUserUsersMeGetResponsesContentApplicationJsonSchemaFanCounts(FanvueModel):
    followersCount: float
    subscribersCount: float


class GetCurrentUserUsersMeGetResponsesContentApplicationJsonSchemaContentCounts(FanvueModel):
    imageCount: float
    videoCount: float
    audioCount: float
    postCount: float
    payToViewPostCount: float


class GetCurrentUserGetCurrentUserResponse200(FanvueModel):
    uuid: str
    email: str
    handle: str
    bio: str
    displayName: str
    isCreator: bool
    createdAt: str
    updatedAt: str | None
    avatarUrl: str | None
    bannerUrl: str | None
    likesCount: float | None = None
    fanCounts: GetCurrentUserUsersMeGetResponsesContentApplicationJsonSchemaFanCounts | None = None
    contentCounts: GetCurrentUserUsersMeGetResponsesContentApplicationJsonSchemaContentCounts | None = None


class ListChatsChatsGetResponsesContentApplicationJsonSchemaDataItemsUser(FanvueModel):
    uuid: str
    handle: str
    displayName: str
    nickname: str | None
    isTopSpender: bool
    avatarUrl: str | None
    registeredAt: str


class ListChatsChatsGetResponsesContentApplicationJsonSchemaDataItemsLastMessage(FanvueModel):
    text: str | None
    type: str  # e.g. SINGLE_RECIPIENT, TIP, AUTOMATED_FIRST_MESSAGE_REPLY, etc.
    uuid: str
    sentAt: str
    hasMedia: bool | None
    mediaType: Literal['image', 'video', 'audio', 'document'] | None
    senderUuid: str
    sentByUserId: str | None


class ListChatsChatsGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    createdAt: str
    lastMessageAt: str | None
    isRead: bool
    isMuted: bool
    unreadMessagesCount: float
    user: ListChatsChatsGetResponsesContentApplicationJsonSchemaDataItemsUser
    lastMessage: ListChatsChatsGetResponsesContentApplicationJsonSchemaDataItemsLastMessage | None


class ListChatsChatsGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class ListChatsListChatsResponse200(FanvueModel):
    data: list[ListChatsChatsGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: ListChatsChatsGetResponsesContentApplicationJsonSchemaPagination


class GetUnreadChatsCountChatsUnreadGetResponsesContentApplicationJsonSchemaUnreadNotifications(FanvueModel):
    newFollower: float
    newPostComment: float
    newPostLike: float
    newPurchase: float
    newSubscriber: float
    newTip: float
    newPromotion: float


class GetUnreadChatsCountGetUnreadChatsCountResponse200(FanvueModel):
    unreadChatsCount: float
    unreadMessagesCount: float
    unreadNotifications: GetUnreadChatsCountChatsUnreadGetResponsesContentApplicationJsonSchemaUnreadNotifications


class ListMediaChatsUserUuidMediaGetResponsesContentApplicationJsonSchemaDataItemsVariantsItems(FanvueModel):
    variantType: Literal['main', 'thumbnail', 'thumbnail_gallery', 'blurred']
    displayPosition: float
    url: str | None = None
    width: float | None
    height: float | None
    lengthMs: float | None


class ListMediaChatsUserUuidMediaGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    messageUuid: str
    mediaType: Literal['image', 'video', 'audio', 'document', 'unknown']
    created_at: str
    sentAt: str
    ownerUuid: str
    name: str | None
    variants: list[ListMediaChatsUserUuidMediaGetResponsesContentApplicationJsonSchemaDataItemsVariantsItems] | None = None


class ListMediaListMediaResponse200(FanvueModel):
    data: list[ListMediaChatsUserUuidMediaGetResponsesContentApplicationJsonSchemaDataItems]
    nextCursor: str | None


class CreateChatCreateChatResponse201(FanvueModel):
    message: str


class GetBatchStatusesChatsStatusesPostResponsesContentApplicationJsonSchema(FanvueModel):
    isOnline: bool
    lastSeenAt: str | None


class ListMessagesChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsSender(FanvueModel):
    uuid: str
    handle: str


class ListMessagesChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsRecipient(FanvueModel):
    uuid: str | None = None
    handle: str | None = None


class ListMessagesChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsPricingUsd(FanvueModel):
    price: float


class ListMessagesChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsPricing(FanvueModel):
    USD: ListMessagesChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsPricingUsd


class ListMessagesChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    text: str | None
    sentAt: str | None
    sender: ListMessagesChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsSender
    recipient: ListMessagesChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsRecipient
    hasMedia: bool | None
    mediaType: Literal['image', 'video', 'audio', 'document'] | None
    mediaUuids: list[str]
    type: str  # e.g. SINGLE_RECIPIENT, TIP, AUTOMATED_FIRST_MESSAGE_REPLY, etc.
    pricing: ListMessagesChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsPricing | None
    purchasedAt: str | None
    sentByUserId: str | None


class ListMessagesChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class ListMessagesListMessagesResponse200(FanvueModel):
    data: list[ListMessagesChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: ListMessagesChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaPagination


class SendMessageSendMessageResponse201(FanvueModel):
    messageUuid: str


class SendMassMessageSendMassMessageResponse201(FanvueModel):
    id: str
    recipientCount: float
    createdAt: str


class ListTemplateMessagesChatsTemplatesGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    text: str | None
    price: float | None
    mediaUuids: list[str]
    folderName: str | None


class ListTemplateMessagesChatsTemplatesGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class ListTemplateMessagesListTemplateMessagesResponse200(FanvueModel):
    data: list[ListTemplateMessagesChatsTemplatesGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: ListTemplateMessagesChatsTemplatesGetResponsesContentApplicationJsonSchemaPagination


class GetTemplateMessageGetTemplateMessageResponse200(FanvueModel):
    uuid: str
    text: str | None
    price: float | None
    mediaUuids: list[str]
    folderName: str | None


class GetSmartListsChatsListsSmartGetResponsesContentApplicationJsonSchemaItems(FanvueModel):
    name: str
    uuid: Literal['subscribers', 'auto_renewing', 'non_renewing', 'followers', 'free_trial_subscribers', 'expired_subscribers', 'spent_more_than_50']
    count: float


class GetSmartListMembersChatsListsSmartUuidGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    displayName: str
    handle: str
    isCreator: bool


class GetSmartListMembersChatsListsSmartUuidGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class GetSmartListMembersGetSmartListMembersResponse200(FanvueModel):
    data: list[GetSmartListMembersChatsListsSmartUuidGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: GetSmartListMembersChatsListsSmartUuidGetResponsesContentApplicationJsonSchemaPagination


class GetCustomListsChatsListsCustomGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    name: str
    membersCount: float
    createdAt: str


class GetCustomListsChatsListsCustomGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class GetCustomListsGetCustomListsResponse200(FanvueModel):
    data: list[GetCustomListsChatsListsCustomGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: GetCustomListsChatsListsCustomGetResponsesContentApplicationJsonSchemaPagination


class GetCustomListMembersChatsListsCustomUuidGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    displayName: str
    handle: str
    isCreator: bool


class GetCustomListMembersChatsListsCustomUuidGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class GetCustomListMembersGetCustomListMembersResponse200(FanvueModel):
    data: list[GetCustomListMembersChatsListsCustomUuidGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: GetCustomListMembersChatsListsCustomUuidGetResponsesContentApplicationJsonSchemaPagination


class CreateCustomListCreateCustomListResponse201(FanvueModel):
    uuid: str
    name: str
    createdAt: str


class AddMembersToCustomListAddMembersToCustomListResponse201(FanvueModel):
    added: float
    skipped: float


class GetPostsPostsGetResponsesContentApplicationJsonSchemaDataItemsTips(FanvueModel):
    count: float
    totalGross: float
    totalNet: float


class GetPostsPostsGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    createdAt: str
    text: str | None
    price: float | None
    audience: Literal['subscribers', 'followers-and-subscribers']
    publishAt: str | None
    publishedAt: str | None
    expiresAt: str | None
    mediaUuids: list[str]
    isPinned: bool
    likesCount: float
    commentsCount: float
    tips: GetPostsPostsGetResponsesContentApplicationJsonSchemaDataItemsTips


class GetPostsPostsGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class GetPostsGetPostsResponse200(FanvueModel):
    data: list[GetPostsPostsGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: GetPostsPostsGetResponsesContentApplicationJsonSchemaPagination


class GetPostByUuidPostsUuidGetResponsesContentApplicationJsonSchemaTips(FanvueModel):
    count: float
    totalGross: float
    totalNet: float


class GetPostByUuidGetPostByUuidResponse200(FanvueModel):
    uuid: str
    createdAt: str
    text: str | None
    price: float | None
    audience: Literal['subscribers', 'followers-and-subscribers']
    publishAt: str | None
    publishedAt: str | None
    expiresAt: str | None
    mediaUuids: list[str]
    isPinned: bool
    likesCount: float
    commentsCount: float
    tips: GetPostByUuidPostsUuidGetResponsesContentApplicationJsonSchemaTips


class GetPostTipsPostsUuidTipsGetResponsesContentApplicationJsonSchemaDataItemsUser(FanvueModel):
    uuid: str
    handle: str
    displayName: str
    nickname: str | None
    isTopSpender: bool
    avatarUrl: str | None
    registeredAt: str


class GetPostTipsPostsUuidTipsGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    user: GetPostTipsPostsUuidTipsGetResponsesContentApplicationJsonSchemaDataItemsUser | None
    createdAt: str
    gross: float
    net: float


class GetPostTipsPostsUuidTipsGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class GetPostTipsGetPostTipsResponse200(FanvueModel):
    data: list[GetPostTipsPostsUuidTipsGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: GetPostTipsPostsUuidTipsGetResponsesContentApplicationJsonSchemaPagination


class GetPostLikesPostsUuidLikesGetResponsesContentApplicationJsonSchemaDataItemsUser(FanvueModel):
    uuid: str
    handle: str
    displayName: str
    nickname: str | None
    isTopSpender: bool
    avatarUrl: str | None
    registeredAt: str


class GetPostLikesPostsUuidLikesGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    user: GetPostLikesPostsUuidLikesGetResponsesContentApplicationJsonSchemaDataItemsUser | None
    createdAt: str


class GetPostLikesPostsUuidLikesGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class GetPostLikesGetPostLikesResponse200(FanvueModel):
    data: list[GetPostLikesPostsUuidLikesGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: GetPostLikesPostsUuidLikesGetResponsesContentApplicationJsonSchemaPagination


class GetPostCommentsPostsUuidCommentsGetResponsesContentApplicationJsonSchemaDataItemsUser(FanvueModel):
    uuid: str
    handle: str
    displayName: str
    nickname: str | None
    isTopSpender: bool


class GetPostCommentsPostsUuidCommentsGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    text: str
    user: GetPostCommentsPostsUuidCommentsGetResponsesContentApplicationJsonSchemaDataItemsUser | None
    createdAt: str
    updatedAt: str | None


class GetPostCommentsPostsUuidCommentsGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class GetPostCommentsGetPostCommentsResponse200(FanvueModel):
    data: list[GetPostCommentsPostsUuidCommentsGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: GetPostCommentsPostsUuidCommentsGetResponsesContentApplicationJsonSchemaPagination


class CreatePostCreatePostResponse201(FanvueModel):
    uuid: str
    createdAt: str
    text: str | None
    price: float | None
    audience: Literal['subscribers', 'followers-and-subscribers']
    publishAt: str | None
    publishedAt: str | None
    expiresAt: str | None


class ListFollowersFollowersGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    handle: str
    displayName: str
    nickname: str | None
    isTopSpender: bool
    avatarUrl: str | None
    registeredAt: str


class ListFollowersFollowersGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class ListFollowersListFollowersResponse200(FanvueModel):
    data: list[ListFollowersFollowersGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: ListFollowersFollowersGetResponsesContentApplicationJsonSchemaPagination


class ListSubscribersSubscribersGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    handle: str
    displayName: str
    nickname: str | None
    isTopSpender: bool
    avatarUrl: str | None
    registeredAt: str


class ListSubscribersSubscribersGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class ListSubscribersListSubscribersResponse200(FanvueModel):
    data: list[ListSubscribersSubscribersGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: ListSubscribersSubscribersGetResponsesContentApplicationJsonSchemaPagination


class GetEarningsInsightsEarningsGetResponsesContentApplicationJsonSchemaDataItemsUser(FanvueModel):
    uuid: str
    handle: str
    displayName: str
    nickname: str | None
    isTopSpender: bool


class GetEarningsInsightsEarningsGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    date: str
    gross: float
    net: float
    currency: str | None
    source: Literal['all', 'affiliate', 'mediaLink', 'message', 'post', 'referral', 'renewal', 'subscription', 'tip', 'giveaway']
    messageUuid: str | None = None
    postUuid: str | None = None
    user: GetEarningsInsightsEarningsGetResponsesContentApplicationJsonSchemaDataItemsUser | None


class GetEarningsGetEarningsResponse200(FanvueModel):
    data: list[GetEarningsInsightsEarningsGetResponsesContentApplicationJsonSchemaDataItems]
    nextCursor: str | None


class GetTopSpendersInsightsTopSpendersGetResponsesContentApplicationJsonSchemaDataItemsUser(FanvueModel):
    uuid: str
    handle: str
    displayName: str
    nickname: str | None
    isTopSpender: bool
    avatarUrl: str | None
    registeredAt: str


class GetTopSpendersInsightsTopSpendersGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    gross: float
    net: float
    messages: float
    user: GetTopSpendersInsightsTopSpendersGetResponsesContentApplicationJsonSchemaDataItemsUser


class GetTopSpendersInsightsTopSpendersGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class GetTopSpendersGetTopSpendersResponse200(FanvueModel):
    data: list[GetTopSpendersInsightsTopSpendersGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: GetTopSpendersInsightsTopSpendersGetResponsesContentApplicationJsonSchemaPagination


class GetSubscribersInsightsSubscribersGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    date: str
    total: float
    newSubscribersCount: float
    cancelledSubscribersCount: float


class GetSubscribersGetSubscribersResponse200(FanvueModel):
    data: list[GetSubscribersInsightsSubscribersGetResponsesContentApplicationJsonSchemaDataItems]
    nextCursor: str | None


class GetFanInsightsInsightsFansUserUuidGetResponsesContentApplicationJsonSchemaSpendingTotal(FanvueModel):
    gross: float


class GetFanInsightsInsightsFansUserUuidGetResponsesContentApplicationJsonSchemaSpendingMaxSinglePayment(FanvueModel):
    gross: float


class GetFanInsightsInsightsFansUserUuidGetResponsesContentApplicationJsonSchemaSpendingSources(FanvueModel):
    gross: float


class GetFanInsightsInsightsFansUserUuidGetResponsesContentApplicationJsonSchemaSpending(FanvueModel):
    lastPurchaseAt: str | None
    total: GetFanInsightsInsightsFansUserUuidGetResponsesContentApplicationJsonSchemaSpendingTotal
    maxSinglePayment: GetFanInsightsInsightsFansUserUuidGetResponsesContentApplicationJsonSchemaSpendingMaxSinglePayment
    sources: dict[str, GetFanInsightsInsightsFansUserUuidGetResponsesContentApplicationJsonSchemaSpendingSources]


class GetFanInsightsInsightsFansUserUuidGetResponsesContentApplicationJsonSchemaSubscription(FanvueModel):
    createdAt: str | None
    renewsAt: str | None
    autoRenewalEnabled: bool


class GetFanInsightsGetFanInsightsResponse200(FanvueModel):
    status: Literal['subscriber', 'expired', 'follower', 'not_contactable']
    spending: GetFanInsightsInsightsFansUserUuidGetResponsesContentApplicationJsonSchemaSpending
    subscription: GetFanInsightsInsightsFansUserUuidGetResponsesContentApplicationJsonSchemaSubscription


class GetUserMediaMediaGetResponsesContentApplicationJsonSchemaDataItems0(FanvueModel):
    uuid: str
    status: Literal['created', 'processing', 'ready', 'error']


class GetUserMediaMediaGetResponsesContentApplicationJsonSchemaDataItemsOneOf1VariantsItems(FanvueModel):
    uuid: str
    variantType: Literal['blurred', 'main', 'thumbnail', 'thumbnail_gallery']
    displayPosition: float
    url: str | None = None
    width: float | None
    height: float | None
    lengthMs: float | None


class GetUserMediaMediaGetResponsesContentApplicationJsonSchemaDataItems1(FanvueModel):
    uuid: str
    status: Literal['created', 'processing', 'ready', 'error']
    createdAt: str
    url: str | None = None
    caption: str | None
    description: str | None
    name: str | None
    mediaType: Literal['image', 'video', 'audio', 'document']
    recommendedPrice: float | None
    variants: list[GetUserMediaMediaGetResponsesContentApplicationJsonSchemaDataItemsOneOf1VariantsItems] | None = None
    purchasedByFan: bool | None = None


class GetUserMediaMediaGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class GetUserMediaGetUserMediaResponse200(FanvueModel):
    data: list[GetUserMediaMediaGetResponsesContentApplicationJsonSchemaDataItems0 | GetUserMediaMediaGetResponsesContentApplicationJsonSchemaDataItems1]
    pagination: GetUserMediaMediaGetResponsesContentApplicationJsonSchemaPagination


class GetUserMediaByUuidGetUserMediaByUuidResponse2000(FanvueModel):
    uuid: str
    status: Literal['created', 'processing', 'ready', 'error']


class GetUserMediaByUuidMediaUuidGetResponsesContentApplicationJsonSchemaOneOf1VariantsItems(FanvueModel):
    uuid: str
    variantType: Literal['blurred', 'main', 'thumbnail', 'thumbnail_gallery']
    displayPosition: float
    url: str | None = None
    width: float | None
    height: float | None
    lengthMs: float | None


class GetUserMediaByUuidGetUserMediaByUuidResponse2001(FanvueModel):
    uuid: str
    status: Literal['created', 'processing', 'ready', 'error']
    createdAt: str
    url: str | None = None
    caption: str | None
    description: str | None
    name: str | None
    mediaType: Literal['image', 'video', 'audio', 'document']
    recommendedPrice: float | None
    variants: list[GetUserMediaByUuidMediaUuidGetResponsesContentApplicationJsonSchemaOneOf1VariantsItems] | None = None
    purchasedByFan: bool | None = None


class CreateUploadSessionCreateUploadSessionResponse200(FanvueModel):
    mediaUuid: str
    uploadId: str


class GetUploadPartUrlResponsePayload(FanvueModel):
    pass


class CompleteUploadSessionCompleteUploadSessionResponse200(FanvueModel):
    status: Literal['created', 'processing', 'ready', 'error']


class ListTrackingLinksTrackingLinksGetResponsesContentApplicationJsonSchemaDataItemsEngagement(FanvueModel):
    acquiredSubscribers: float
    acquiredFollowers: float


class ListTrackingLinksTrackingLinksGetResponsesContentApplicationJsonSchemaDataItemsEarnings(FanvueModel):
    totalGross: float
    totalNet: float


class ListTrackingLinksTrackingLinksGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    name: str
    linkUrl: str
    externalSocialPlatform: Literal['facebook', 'instagram', 'other', 'reddit', 'snapchat', 'tiktok', 'twitter', 'youtube']
    createdAt: str
    clicks: float
    engagement: ListTrackingLinksTrackingLinksGetResponsesContentApplicationJsonSchemaDataItemsEngagement
    earnings: ListTrackingLinksTrackingLinksGetResponsesContentApplicationJsonSchemaDataItemsEarnings | None


class ListTrackingLinksListTrackingLinksResponse200(FanvueModel):
    data: list[ListTrackingLinksTrackingLinksGetResponsesContentApplicationJsonSchemaDataItems]
    nextCursor: str | None


class CreateTrackingLinkTrackingLinksPostResponsesContentApplicationJsonSchemaEngagement(FanvueModel):
    acquiredSubscribers: float
    acquiredFollowers: float


class CreateTrackingLinkTrackingLinksPostResponsesContentApplicationJsonSchemaEarnings(FanvueModel):
    totalGross: float
    totalNet: float


class CreateTrackingLinkCreateTrackingLinkResponse201(FanvueModel):
    uuid: str
    name: str
    linkUrl: str
    externalSocialPlatform: Literal['facebook', 'instagram', 'other', 'reddit', 'snapchat', 'tiktok', 'twitter', 'youtube']
    createdAt: str
    clicks: float
    engagement: CreateTrackingLinkTrackingLinksPostResponsesContentApplicationJsonSchemaEngagement
    earnings: CreateTrackingLinkTrackingLinksPostResponsesContentApplicationJsonSchemaEarnings | None


class ListVaultFoldersVaultFoldersGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    name: str
    createdAt: str
    mediaCount: float


class ListVaultFoldersVaultFoldersGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class ListVaultFoldersListVaultFoldersResponse200(FanvueModel):
    data: list[ListVaultFoldersVaultFoldersGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: ListVaultFoldersVaultFoldersGetResponsesContentApplicationJsonSchemaPagination


class CreateVaultFolderCreateVaultFolderResponse201(FanvueModel):
    name: str
    createdAt: str
    mediaCount: float


class GetVaultFolderGetVaultFolderResponse200(FanvueModel):
    name: str
    createdAt: str
    mediaCount: float


class ListVaultFolderMediaVaultFoldersFolderNameMediaGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    name: str | None
    createdAt: str
    mediaType: str


class ListVaultFolderMediaVaultFoldersFolderNameMediaGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class ListVaultFolderMediaListVaultFolderMediaResponse200(FanvueModel):
    data: list[ListVaultFolderMediaVaultFoldersFolderNameMediaGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: ListVaultFolderMediaVaultFoldersFolderNameMediaGetResponsesContentApplicationJsonSchemaPagination


class AttachMediaToVaultFolderAttachMediaToVaultFolderResponse201(FanvueModel):
    addedCount: float


class ListCreatorsCreatorsGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    handle: str
    displayName: str
    nickname: str | None
    isTopSpender: bool
    avatarUrl: str | None
    registeredAt: str
    role: str | None = None


class ListCreatorsCreatorsGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class ListCreatorsListCreatorsResponse200(FanvueModel):
    data: list[ListCreatorsCreatorsGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: ListCreatorsCreatorsGetResponsesContentApplicationJsonSchemaPagination


class ListTeamMembersAgenciesTeamMembersGetResponsesContentApplicationJsonSchemaItemsCreatorAccessItems(FanvueModel):
    uuid: str
    role: Literal['ADMIN', 'CHATTER']


class ListTeamMembersAgenciesTeamMembersGetResponsesContentApplicationJsonSchemaItems(FanvueModel):
    uuid: str
    isAdmin: bool
    nickname: str | None
    email: str
    displayName: str
    creatorAccess: list[ListTeamMembersAgenciesTeamMembersGetResponsesContentApplicationJsonSchemaItemsCreatorAccessItems]


class UpdateTeamMemberAgenciesTeamMembersUserIdPutResponsesContentApplicationJsonSchemaCreatorAccessItems(FanvueModel):
    uuid: str
    role: Literal['ADMIN', 'CHATTER']


class UpdateTeamMemberUpdateTeamMemberResponse200(FanvueModel):
    uuid: str
    isAdmin: bool
    nickname: str | None
    email: str
    displayName: str
    creatorAccess: list[UpdateTeamMemberAgenciesTeamMembersUserIdPutResponsesContentApplicationJsonSchemaCreatorAccessItems]


class ListCreatorFollowersCreatorsCreatorUserUuidFollowersGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    handle: str
    displayName: str
    nickname: str | None
    isTopSpender: bool
    avatarUrl: str | None
    registeredAt: str


class ListCreatorFollowersCreatorsCreatorUserUuidFollowersGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class ListCreatorFollowersListCreatorFollowersResponse200(FanvueModel):
    data: list[ListCreatorFollowersCreatorsCreatorUserUuidFollowersGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: ListCreatorFollowersCreatorsCreatorUserUuidFollowersGetResponsesContentApplicationJsonSchemaPagination


class ListCreatorSubscribersCreatorsCreatorUserUuidSubscribersGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    handle: str
    displayName: str
    nickname: str | None
    isTopSpender: bool
    avatarUrl: str | None
    registeredAt: str


class ListCreatorSubscribersCreatorsCreatorUserUuidSubscribersGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class ListCreatorSubscribersListCreatorSubscribersResponse200(FanvueModel):
    data: list[ListCreatorSubscribersCreatorsCreatorUserUuidSubscribersGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: ListCreatorSubscribersCreatorsCreatorUserUuidSubscribersGetResponsesContentApplicationJsonSchemaPagination


class ListCreatorChatsCreatorsCreatorUserUuidChatsGetResponsesContentApplicationJsonSchemaDataItemsUser(FanvueModel):
    uuid: str
    handle: str
    displayName: str
    nickname: str | None
    isTopSpender: bool
    avatarUrl: str | None
    registeredAt: str


class ListCreatorChatsCreatorsCreatorUserUuidChatsGetResponsesContentApplicationJsonSchemaDataItemsLastMessage(FanvueModel):
    text: str | None
    type: str  # e.g. SINGLE_RECIPIENT, TIP, AUTOMATED_FIRST_MESSAGE_REPLY, etc.
    uuid: str
    sentAt: str
    hasMedia: bool | None
    mediaType: Literal['image', 'video', 'audio', 'document'] | None
    senderUuid: str
    sentByUserId: str | None


class ListCreatorChatsCreatorsCreatorUserUuidChatsGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    createdAt: str
    lastMessageAt: str | None
    isRead: bool
    isMuted: bool
    unreadMessagesCount: float
    user: ListCreatorChatsCreatorsCreatorUserUuidChatsGetResponsesContentApplicationJsonSchemaDataItemsUser
    lastMessage: ListCreatorChatsCreatorsCreatorUserUuidChatsGetResponsesContentApplicationJsonSchemaDataItemsLastMessage | None


class ListCreatorChatsCreatorsCreatorUserUuidChatsGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class ListCreatorChatsListCreatorChatsResponse200(FanvueModel):
    data: list[ListCreatorChatsCreatorsCreatorUserUuidChatsGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: ListCreatorChatsCreatorsCreatorUserUuidChatsGetResponsesContentApplicationJsonSchemaPagination


class CreateCreatorChatCreateCreatorChatResponse201(FanvueModel):
    message: str


class GetCreatorSmartListsCreatorsCreatorUserUuidChatsListsSmartGetResponsesContentApplicationJsonSchemaItems(FanvueModel):
    name: str
    uuid: Literal['subscribers', 'auto_renewing', 'non_renewing', 'followers', 'free_trial_subscribers', 'expired_subscribers', 'spent_more_than_50']
    count: float


class GetCreatorSmartListMembersCreatorsCreatorUserUuidChatsListsSmartUuidGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    displayName: str
    handle: str
    isCreator: bool


class GetCreatorSmartListMembersCreatorsCreatorUserUuidChatsListsSmartUuidGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class GetCreatorSmartListMembersGetCreatorSmartListMembersResponse200(FanvueModel):
    data: list[GetCreatorSmartListMembersCreatorsCreatorUserUuidChatsListsSmartUuidGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: GetCreatorSmartListMembersCreatorsCreatorUserUuidChatsListsSmartUuidGetResponsesContentApplicationJsonSchemaPagination


class GetCreatorCustomListsCreatorsCreatorUserUuidChatsListsCustomGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    name: str
    membersCount: float
    createdAt: str


class GetCreatorCustomListsCreatorsCreatorUserUuidChatsListsCustomGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class GetCreatorCustomListsGetCreatorCustomListsResponse200(FanvueModel):
    data: list[GetCreatorCustomListsCreatorsCreatorUserUuidChatsListsCustomGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: GetCreatorCustomListsCreatorsCreatorUserUuidChatsListsCustomGetResponsesContentApplicationJsonSchemaPagination


class GetCreatorCustomListMembersCreatorsCreatorUserUuidChatsListsCustomUuidGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    displayName: str
    handle: str
    isCreator: bool


class GetCreatorCustomListMembersCreatorsCreatorUserUuidChatsListsCustomUuidGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class GetCreatorCustomListMembersGetCreatorCustomListMembersResponse200(FanvueModel):
    data: list[GetCreatorCustomListMembersCreatorsCreatorUserUuidChatsListsCustomUuidGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: GetCreatorCustomListMembersCreatorsCreatorUserUuidChatsListsCustomUuidGetResponsesContentApplicationJsonSchemaPagination


class SendCreatorMassMessageSendCreatorMassMessageResponse201(FanvueModel):
    id: str
    recipientCount: float
    createdAt: str


class SendCreatorMessageSendCreatorMessageResponse201(FanvueModel):
    messageUuid: str


class ListCreatorMessagesCreatorsCreatorUserUuidChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsSender(FanvueModel):
    uuid: str
    handle: str


class ListCreatorMessagesCreatorsCreatorUserUuidChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsRecipient(FanvueModel):
    uuid: str | None = None
    handle: str | None = None


class ListCreatorMessagesCreatorsCreatorUserUuidChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsPricingUsd(FanvueModel):
    price: float


class ListCreatorMessagesCreatorsCreatorUserUuidChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsPricing(FanvueModel):
    USD: ListCreatorMessagesCreatorsCreatorUserUuidChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsPricingUsd


class ListCreatorMessagesCreatorsCreatorUserUuidChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    text: str | None
    sentAt: str | None
    sender: ListCreatorMessagesCreatorsCreatorUserUuidChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsSender
    recipient: ListCreatorMessagesCreatorsCreatorUserUuidChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsRecipient
    hasMedia: bool | None
    mediaType: Literal['image', 'video', 'audio', 'document'] | None
    mediaUuids: list[str]
    type: str  # e.g. SINGLE_RECIPIENT, TIP, AUTOMATED_FIRST_MESSAGE_REPLY, etc.
    pricing: ListCreatorMessagesCreatorsCreatorUserUuidChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItemsPricing | None
    purchasedAt: str | None
    sentByUserId: str | None


class ListCreatorMessagesCreatorsCreatorUserUuidChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class ListCreatorMessagesListCreatorMessagesResponse200(FanvueModel):
    data: list[ListCreatorMessagesCreatorsCreatorUserUuidChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: ListCreatorMessagesCreatorsCreatorUserUuidChatsUserUuidMessagesGetResponsesContentApplicationJsonSchemaPagination


class ListCreatorChatMediaCreatorsCreatorUserUuidChatsUserUuidMediaGetResponsesContentApplicationJsonSchemaDataItemsVariantsItems(FanvueModel):
    variantType: Literal['main', 'thumbnail', 'thumbnail_gallery', 'blurred']
    displayPosition: float
    url: str | None = None
    width: float | None
    height: float | None
    lengthMs: float | None


class ListCreatorChatMediaCreatorsCreatorUserUuidChatsUserUuidMediaGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    messageUuid: str
    mediaType: Literal['image', 'video', 'audio', 'document', 'unknown']
    created_at: str
    sentAt: str
    ownerUuid: str
    name: str | None
    variants: list[ListCreatorChatMediaCreatorsCreatorUserUuidChatsUserUuidMediaGetResponsesContentApplicationJsonSchemaDataItemsVariantsItems] | None = None


class ListCreatorChatMediaListCreatorChatMediaResponse200(FanvueModel):
    data: list[ListCreatorChatMediaCreatorsCreatorUserUuidChatsUserUuidMediaGetResponsesContentApplicationJsonSchemaDataItems]
    nextCursor: str | None


class GetCreatorEarningsCreatorsCreatorUserUuidInsightsEarningsGetResponsesContentApplicationJsonSchemaDataItemsUser(FanvueModel):
    uuid: str
    handle: str
    displayName: str
    nickname: str | None
    isTopSpender: bool


class GetCreatorEarningsCreatorsCreatorUserUuidInsightsEarningsGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    date: str
    gross: float
    net: float
    currency: str | None
    source: Literal['all', 'affiliate', 'mediaLink', 'message', 'post', 'referral', 'renewal', 'subscription', 'tip', 'giveaway']
    messageUuid: str | None = None
    postUuid: str | None = None
    user: GetCreatorEarningsCreatorsCreatorUserUuidInsightsEarningsGetResponsesContentApplicationJsonSchemaDataItemsUser | None


class GetCreatorEarningsGetCreatorEarningsResponse200(FanvueModel):
    data: list[GetCreatorEarningsCreatorsCreatorUserUuidInsightsEarningsGetResponsesContentApplicationJsonSchemaDataItems]
    nextCursor: str | None


class GetCreatorTopSpendersCreatorsCreatorUserUuidInsightsTopSpendersGetResponsesContentApplicationJsonSchemaDataItemsUser(FanvueModel):
    uuid: str
    handle: str
    displayName: str
    nickname: str | None
    isTopSpender: bool
    avatarUrl: str | None
    registeredAt: str


class GetCreatorTopSpendersCreatorsCreatorUserUuidInsightsTopSpendersGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    gross: float
    net: float
    messages: float
    user: GetCreatorTopSpendersCreatorsCreatorUserUuidInsightsTopSpendersGetResponsesContentApplicationJsonSchemaDataItemsUser


class GetCreatorTopSpendersCreatorsCreatorUserUuidInsightsTopSpendersGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class GetCreatorTopSpendersGetCreatorTopSpendersResponse200(FanvueModel):
    data: list[GetCreatorTopSpendersCreatorsCreatorUserUuidInsightsTopSpendersGetResponsesContentApplicationJsonSchemaDataItems]
    pagination: GetCreatorTopSpendersCreatorsCreatorUserUuidInsightsTopSpendersGetResponsesContentApplicationJsonSchemaPagination


class GetCreatorSubscribersCreatorsCreatorUserUuidInsightsSubscribersGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    date: str
    total: float
    newSubscribersCount: float
    cancelledSubscribersCount: float


class GetCreatorSubscribersGetCreatorSubscribersResponse200(FanvueModel):
    data: list[GetCreatorSubscribersCreatorsCreatorUserUuidInsightsSubscribersGetResponsesContentApplicationJsonSchemaDataItems]
    nextCursor: str | None


class GetCreatorMediaCreatorsCreatorUserUuidMediaGetResponsesContentApplicationJsonSchemaDataItems0(FanvueModel):
    uuid: str
    status: Literal['created', 'processing', 'ready', 'error']


class GetCreatorMediaCreatorsCreatorUserUuidMediaGetResponsesContentApplicationJsonSchemaDataItemsOneOf1VariantsItems(FanvueModel):
    uuid: str
    variantType: Literal['blurred', 'main', 'thumbnail', 'thumbnail_gallery']
    displayPosition: float
    url: str | None = None
    width: float | None
    height: float | None
    lengthMs: float | None


class GetCreatorMediaCreatorsCreatorUserUuidMediaGetResponsesContentApplicationJsonSchemaDataItems1(FanvueModel):
    uuid: str
    status: Literal['created', 'processing', 'ready', 'error']
    createdAt: str
    url: str | None = None
    caption: str | None
    description: str | None
    name: str | None
    mediaType: Literal['image', 'video', 'audio', 'document']
    recommendedPrice: float | None
    variants: list[GetCreatorMediaCreatorsCreatorUserUuidMediaGetResponsesContentApplicationJsonSchemaDataItemsOneOf1VariantsItems] | None = None
    purchasedByFan: bool | None = None


class GetCreatorMediaCreatorsCreatorUserUuidMediaGetResponsesContentApplicationJsonSchemaPagination(FanvueModel):
    page: float
    size: float
    hasMore: bool


class GetCreatorMediaGetCreatorMediaResponse200(FanvueModel):
    data: list[GetCreatorMediaCreatorsCreatorUserUuidMediaGetResponsesContentApplicationJsonSchemaDataItems0 | GetCreatorMediaCreatorsCreatorUserUuidMediaGetResponsesContentApplicationJsonSchemaDataItems1]
    pagination: GetCreatorMediaCreatorsCreatorUserUuidMediaGetResponsesContentApplicationJsonSchemaPagination


class GetCreatorMediaByUuidGetCreatorMediaByUuidResponse2000(FanvueModel):
    uuid: str
    status: Literal['created', 'processing', 'ready', 'error']


class GetCreatorMediaByUuidCreatorsCreatorUserUuidMediaUuidGetResponsesContentApplicationJsonSchemaOneOf1VariantsItems(FanvueModel):
    uuid: str
    variantType: Literal['blurred', 'main', 'thumbnail', 'thumbnail_gallery']
    displayPosition: float
    url: str | None = None
    width: float | None
    height: float | None
    lengthMs: float | None


class GetCreatorMediaByUuidGetCreatorMediaByUuidResponse2001(FanvueModel):
    uuid: str
    status: Literal['created', 'processing', 'ready', 'error']
    createdAt: str
    url: str | None = None
    caption: str | None
    description: str | None
    name: str | None
    mediaType: Literal['image', 'video', 'audio', 'document']
    recommendedPrice: float | None
    variants: list[GetCreatorMediaByUuidCreatorsCreatorUserUuidMediaUuidGetResponsesContentApplicationJsonSchemaOneOf1VariantsItems] | None = None
    purchasedByFan: bool | None = None


class CreateCreatorUploadSessionCreateCreatorUploadSessionResponse200(FanvueModel):
    mediaUuid: str
    uploadId: str


class GetCreatorUploadPartUrlResponsePayload(FanvueModel):
    pass


class CompleteCreatorUploadSessionCompleteCreatorUploadSessionResponse200(FanvueModel):
    status: Literal['created', 'processing', 'ready', 'error']


class CreateCreatorPostCreateCreatorPostResponse201(FanvueModel):
    uuid: str
    createdAt: str
    text: str | None
    price: float | None
    audience: Literal['subscribers', 'followers-and-subscribers']
    publishAt: str | None
    publishedAt: str | None
    expiresAt: str | None


class ListCreatorTrackingLinksCreatorsCreatorUserUuidTrackingLinksGetResponsesContentApplicationJsonSchemaDataItemsEngagement(FanvueModel):
    acquiredSubscribers: float
    acquiredFollowers: float


class ListCreatorTrackingLinksCreatorsCreatorUserUuidTrackingLinksGetResponsesContentApplicationJsonSchemaDataItemsEarnings(FanvueModel):
    totalGross: float
    totalNet: float


class ListCreatorTrackingLinksCreatorsCreatorUserUuidTrackingLinksGetResponsesContentApplicationJsonSchemaDataItems(FanvueModel):
    uuid: str
    name: str
    linkUrl: str
    externalSocialPlatform: Literal['facebook', 'instagram', 'other', 'reddit', 'snapchat', 'tiktok', 'twitter', 'youtube']
    createdAt: str
    clicks: float
    engagement: ListCreatorTrackingLinksCreatorsCreatorUserUuidTrackingLinksGetResponsesContentApplicationJsonSchemaDataItemsEngagement
    earnings: ListCreatorTrackingLinksCreatorsCreatorUserUuidTrackingLinksGetResponsesContentApplicationJsonSchemaDataItemsEarnings | None


class ListCreatorTrackingLinksListCreatorTrackingLinksResponse200(FanvueModel):
    data: list[ListCreatorTrackingLinksCreatorsCreatorUserUuidTrackingLinksGetResponsesContentApplicationJsonSchemaDataItems]
    nextCursor: str | None


class CreateCreatorTrackingLinkCreatorsCreatorUserUuidTrackingLinksPostResponsesContentApplicationJsonSchemaEngagement(FanvueModel):
    acquiredSubscribers: float
    acquiredFollowers: float


class CreateCreatorTrackingLinkCreatorsCreatorUserUuidTrackingLinksPostResponsesContentApplicationJsonSchemaEarnings(FanvueModel):
    totalGross: float
    totalNet: float


class CreateCreatorTrackingLinkCreateCreatorTrackingLinkResponse201(FanvueModel):
    uuid: str
    name: str
    linkUrl: str
    externalSocialPlatform: Literal['facebook', 'instagram', 'other', 'reddit', 'snapchat', 'tiktok', 'twitter', 'youtube']
    createdAt: str
    clicks: float
    engagement: CreateCreatorTrackingLinkCreatorsCreatorUserUuidTrackingLinksPostResponsesContentApplicationJsonSchemaEngagement
    earnings: CreateCreatorTrackingLinkCreatorsCreatorUserUuidTrackingLinksPostResponsesContentApplicationJsonSchemaEarnings | None


GetCurrentUserResponse: TypeAlias = GetCurrentUserGetCurrentUserResponse200
ListChatsResponse: TypeAlias = ListChatsListChatsResponse200
GetUnreadChatsCountResponse: TypeAlias = GetUnreadChatsCountGetUnreadChatsCountResponse200
ListMediaResponse: TypeAlias = ListMediaListMediaResponse200
CreateChatResponse: TypeAlias = CreateChatCreateChatResponse201
GetBatchStatusesResponse: TypeAlias = dict[str, GetBatchStatusesChatsStatusesPostResponsesContentApplicationJsonSchema]
ListMessagesResponse: TypeAlias = ListMessagesListMessagesResponse200
SendMessageResponse: TypeAlias = SendMessageSendMessageResponse201
SendMassMessageResponse: TypeAlias = SendMassMessageSendMassMessageResponse201
ListTemplateMessagesResponse: TypeAlias = ListTemplateMessagesListTemplateMessagesResponse200
GetTemplateMessageResponse: TypeAlias = GetTemplateMessageGetTemplateMessageResponse200
GetSmartListsResponse: TypeAlias = list[GetSmartListsChatsListsSmartGetResponsesContentApplicationJsonSchemaItems]
GetSmartListMembersResponse: TypeAlias = GetSmartListMembersGetSmartListMembersResponse200
GetCustomListsResponse: TypeAlias = GetCustomListsGetCustomListsResponse200
GetCustomListMembersResponse: TypeAlias = GetCustomListMembersGetCustomListMembersResponse200
CreateCustomListResponse: TypeAlias = CreateCustomListCreateCustomListResponse201
AddMembersToCustomListResponse: TypeAlias = AddMembersToCustomListAddMembersToCustomListResponse201
GetPostsResponse: TypeAlias = GetPostsGetPostsResponse200
GetPostByUuidResponse: TypeAlias = GetPostByUuidGetPostByUuidResponse200
GetPostTipsResponse: TypeAlias = GetPostTipsGetPostTipsResponse200
GetPostLikesResponse: TypeAlias = GetPostLikesGetPostLikesResponse200
GetPostCommentsResponse: TypeAlias = GetPostCommentsGetPostCommentsResponse200
CreatePostResponse: TypeAlias = CreatePostCreatePostResponse201
ListFollowersResponse: TypeAlias = ListFollowersListFollowersResponse200
ListSubscribersResponse: TypeAlias = ListSubscribersListSubscribersResponse200
GetEarningsResponse: TypeAlias = GetEarningsGetEarningsResponse200
GetTopSpendersResponse: TypeAlias = GetTopSpendersGetTopSpendersResponse200
GetSubscribersResponse: TypeAlias = GetSubscribersGetSubscribersResponse200
GetFanInsightsResponse: TypeAlias = GetFanInsightsGetFanInsightsResponse200
GetUserMediaResponse: TypeAlias = GetUserMediaGetUserMediaResponse200
GetUserMediaByUuidResponse: TypeAlias = GetUserMediaByUuidGetUserMediaByUuidResponse2000 | GetUserMediaByUuidGetUserMediaByUuidResponse2001
CreateUploadSessionResponse: TypeAlias = CreateUploadSessionCreateUploadSessionResponse200
GetUploadPartUrlResponse: TypeAlias = GetUploadPartUrlResponsePayload
CompleteUploadSessionResponse: TypeAlias = CompleteUploadSessionCompleteUploadSessionResponse200
ListTrackingLinksResponse: TypeAlias = ListTrackingLinksListTrackingLinksResponse200
CreateTrackingLinkResponse: TypeAlias = CreateTrackingLinkCreateTrackingLinkResponse201
ListVaultFoldersResponse: TypeAlias = ListVaultFoldersListVaultFoldersResponse200
CreateVaultFolderResponse: TypeAlias = CreateVaultFolderCreateVaultFolderResponse201
GetVaultFolderResponse: TypeAlias = GetVaultFolderGetVaultFolderResponse200
ListVaultFolderMediaResponse: TypeAlias = ListVaultFolderMediaListVaultFolderMediaResponse200
AttachMediaToVaultFolderResponse: TypeAlias = AttachMediaToVaultFolderAttachMediaToVaultFolderResponse201
ListCreatorsResponse: TypeAlias = ListCreatorsListCreatorsResponse200
ListTeamMembersResponse: TypeAlias = list[ListTeamMembersAgenciesTeamMembersGetResponsesContentApplicationJsonSchemaItems]
UpdateTeamMemberResponse: TypeAlias = UpdateTeamMemberUpdateTeamMemberResponse200
ListCreatorFollowersResponse: TypeAlias = ListCreatorFollowersListCreatorFollowersResponse200
ListCreatorSubscribersResponse: TypeAlias = ListCreatorSubscribersListCreatorSubscribersResponse200
ListCreatorChatsResponse: TypeAlias = ListCreatorChatsListCreatorChatsResponse200
CreateCreatorChatResponse: TypeAlias = CreateCreatorChatCreateCreatorChatResponse201
GetCreatorSmartListsResponse: TypeAlias = list[GetCreatorSmartListsCreatorsCreatorUserUuidChatsListsSmartGetResponsesContentApplicationJsonSchemaItems]
GetCreatorSmartListMembersResponse: TypeAlias = GetCreatorSmartListMembersGetCreatorSmartListMembersResponse200
GetCreatorCustomListsResponse: TypeAlias = GetCreatorCustomListsGetCreatorCustomListsResponse200
GetCreatorCustomListMembersResponse: TypeAlias = GetCreatorCustomListMembersGetCreatorCustomListMembersResponse200
SendCreatorMassMessageResponse: TypeAlias = SendCreatorMassMessageSendCreatorMassMessageResponse201
SendCreatorMessageResponse: TypeAlias = SendCreatorMessageSendCreatorMessageResponse201
ListCreatorMessagesResponse: TypeAlias = ListCreatorMessagesListCreatorMessagesResponse200
ListCreatorChatMediaResponse: TypeAlias = ListCreatorChatMediaListCreatorChatMediaResponse200
GetCreatorEarningsResponse: TypeAlias = GetCreatorEarningsGetCreatorEarningsResponse200
GetCreatorTopSpendersResponse: TypeAlias = GetCreatorTopSpendersGetCreatorTopSpendersResponse200
GetCreatorSubscribersResponse: TypeAlias = GetCreatorSubscribersGetCreatorSubscribersResponse200
GetCreatorMediaResponse: TypeAlias = GetCreatorMediaGetCreatorMediaResponse200
GetCreatorMediaByUuidResponse: TypeAlias = GetCreatorMediaByUuidGetCreatorMediaByUuidResponse2000 | GetCreatorMediaByUuidGetCreatorMediaByUuidResponse2001
CreateCreatorUploadSessionResponse: TypeAlias = CreateCreatorUploadSessionCreateCreatorUploadSessionResponse200
GetCreatorUploadPartUrlResponse: TypeAlias = GetCreatorUploadPartUrlResponsePayload
CompleteCreatorUploadSessionResponse: TypeAlias = CompleteCreatorUploadSessionCompleteCreatorUploadSessionResponse200
CreateCreatorPostResponse: TypeAlias = CreateCreatorPostCreateCreatorPostResponse201
ListCreatorTrackingLinksResponse: TypeAlias = ListCreatorTrackingLinksListCreatorTrackingLinksResponse200
CreateCreatorTrackingLinkResponse: TypeAlias = CreateCreatorTrackingLinkCreateCreatorTrackingLinkResponse201


OPERATION_RESPONSE_ADAPTERS: dict[str, TypeAdapter[Any]] = {
    'add_members_to_custom_list': TypeAdapter(AddMembersToCustomListResponse),
    'attach_media_to_vault_folder': TypeAdapter(AttachMediaToVaultFolderResponse),
    'complete_creator_upload_session': TypeAdapter(CompleteCreatorUploadSessionResponse),
    'complete_upload_session': TypeAdapter(CompleteUploadSessionResponse),
    'create_chat': TypeAdapter(CreateChatResponse),
    'create_creator_chat': TypeAdapter(CreateCreatorChatResponse),
    'create_creator_post': TypeAdapter(CreateCreatorPostResponse),
    'create_creator_tracking_link': TypeAdapter(CreateCreatorTrackingLinkResponse),
    'create_creator_upload_session': TypeAdapter(CreateCreatorUploadSessionResponse),
    'create_custom_list': TypeAdapter(CreateCustomListResponse),
    'create_post': TypeAdapter(CreatePostResponse),
    'create_tracking_link': TypeAdapter(CreateTrackingLinkResponse),
    'create_upload_session': TypeAdapter(CreateUploadSessionResponse),
    'create_vault_folder': TypeAdapter(CreateVaultFolderResponse),
    'get_batch_statuses': TypeAdapter(GetBatchStatusesResponse),
    'get_creator_custom_list_members': TypeAdapter(GetCreatorCustomListMembersResponse),
    'get_creator_custom_lists': TypeAdapter(GetCreatorCustomListsResponse),
    'get_creator_earnings': TypeAdapter(GetCreatorEarningsResponse),
    'get_creator_media': TypeAdapter(GetCreatorMediaResponse),
    'get_creator_media_by_uuid': TypeAdapter(GetCreatorMediaByUuidResponse),
    'get_creator_smart_list_members': TypeAdapter(GetCreatorSmartListMembersResponse),
    'get_creator_smart_lists': TypeAdapter(GetCreatorSmartListsResponse),
    'get_creator_subscribers': TypeAdapter(GetCreatorSubscribersResponse),
    'get_creator_top_spenders': TypeAdapter(GetCreatorTopSpendersResponse),
    'get_creator_upload_part_url': TypeAdapter(GetCreatorUploadPartUrlResponse),
    'get_current_user': TypeAdapter(GetCurrentUserResponse),
    'get_custom_list_members': TypeAdapter(GetCustomListMembersResponse),
    'get_custom_lists': TypeAdapter(GetCustomListsResponse),
    'get_earnings': TypeAdapter(GetEarningsResponse),
    'get_fan_insights': TypeAdapter(GetFanInsightsResponse),
    'get_post_by_uuid': TypeAdapter(GetPostByUuidResponse),
    'get_post_comments': TypeAdapter(GetPostCommentsResponse),
    'get_post_likes': TypeAdapter(GetPostLikesResponse),
    'get_post_tips': TypeAdapter(GetPostTipsResponse),
    'get_posts': TypeAdapter(GetPostsResponse),
    'get_smart_list_members': TypeAdapter(GetSmartListMembersResponse),
    'get_smart_lists': TypeAdapter(GetSmartListsResponse),
    'get_subscribers': TypeAdapter(GetSubscribersResponse),
    'get_template_message': TypeAdapter(GetTemplateMessageResponse),
    'get_top_spenders': TypeAdapter(GetTopSpendersResponse),
    'get_unread_chats_count': TypeAdapter(GetUnreadChatsCountResponse),
    'get_upload_part_url': TypeAdapter(GetUploadPartUrlResponse),
    'get_user_media': TypeAdapter(GetUserMediaResponse),
    'get_user_media_by_uuid': TypeAdapter(GetUserMediaByUuidResponse),
    'get_vault_folder': TypeAdapter(GetVaultFolderResponse),
    'list_chats': TypeAdapter(ListChatsResponse),
    'list_creator_chat_media': TypeAdapter(ListCreatorChatMediaResponse),
    'list_creator_chats': TypeAdapter(ListCreatorChatsResponse),
    'list_creator_followers': TypeAdapter(ListCreatorFollowersResponse),
    'list_creator_messages': TypeAdapter(ListCreatorMessagesResponse),
    'list_creator_subscribers': TypeAdapter(ListCreatorSubscribersResponse),
    'list_creator_tracking_links': TypeAdapter(ListCreatorTrackingLinksResponse),
    'list_creators': TypeAdapter(ListCreatorsResponse),
    'list_followers': TypeAdapter(ListFollowersResponse),
    'list_media': TypeAdapter(ListMediaResponse),
    'list_messages': TypeAdapter(ListMessagesResponse),
    'list_subscribers': TypeAdapter(ListSubscribersResponse),
    'list_team_members': TypeAdapter(ListTeamMembersResponse),
    'list_template_messages': TypeAdapter(ListTemplateMessagesResponse),
    'list_tracking_links': TypeAdapter(ListTrackingLinksResponse),
    'list_vault_folder_media': TypeAdapter(ListVaultFolderMediaResponse),
    'list_vault_folders': TypeAdapter(ListVaultFoldersResponse),
    'send_creator_mass_message': TypeAdapter(SendCreatorMassMessageResponse),
    'send_creator_message': TypeAdapter(SendCreatorMessageResponse),
    'send_mass_message': TypeAdapter(SendMassMessageResponse),
    'send_message': TypeAdapter(SendMessageResponse),
    'update_team_member': TypeAdapter(UpdateTeamMemberResponse),
}


def parse_operation_response(operation_id: str, payload: ResponseData) -> Any:
    if payload is None or isinstance(payload, bytes):
        return payload

    adapter = OPERATION_RESPONSE_ADAPTERS.get(operation_id)
    if adapter is None:
        return payload

    return adapter.validate_python(payload)